name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image of frontend
        uses: docker/build-push-action@v3
        with:
          context: ./front
          file:  ./front/Dockerfile
          push: true
          tags: tecktv/bobapp-front:latest

      - name: Build and Push Docker Image of backend
        uses: docker/build-push-action@v3
        with:
          context: ./back
          file:  ./back/Dockerfile
          push: true
          tags: tecktv/bobapp-back:latest

