name: Frontend run tests & reports

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        working-directory: front
        run: npm ci

      - name: Run tests and generate reports
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: front
       

      - name: Upload Karma report artifact
        uses: actions/upload-artifact@v3
        with:
          name: Karma-report
          path: front/coverage/bobapp/app
